/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IpemarohilJakarta;
import java.awt.Color;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Me
 */

public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    static String a,b,c;
    Color DefaultColor,ClickedColor,Defaultlabelcolor,Clickedlabelcolor;
    
    public MainPage() {
        initComponents();
        connect();
        datapengurus();
        dataanggota();
        dataalumni();
        DefaultColor = new Color(51,51,51); 
        ClickedColor = new Color (255,255,255);
        Defaultlabelcolor = new Color(255,255,255);
        Clickedlabelcolor = new Color(0,0,0);
        mainpagebtn.setBackground(DefaultColor);
        data_anggota_btn.setBackground(DefaultColor);
        data_alumni_btn.setBackground(DefaultColor);
        logout.setBackground(DefaultColor);
        data_pengurus_btn.setBackground(DefaultColor);
        data_program_kerja_btn.setBackground(DefaultColor);
         mainpage_label.setForeground(Defaultlabelcolor);
         data_anggota_label.setForeground(Defaultlabelcolor);
         logout_label.setForeground(Defaultlabelcolor);
         data_pengurus_label.setForeground(Defaultlabelcolor);
         data_alumni_label.setForeground(Defaultlabelcolor);
         data_program_kerja_label.setForeground(Defaultlabelcolor);
         logout_label.setForeground(Defaultlabelcolor);
        ActionListener ac1=new ActionListener(){
           @Override public void actionPerformed(ActionEvent e){
             a=lb1MovingText.getText();
             b=a.substring(0, 1);
             c=a.substring(1, a.length());
             lb1MovingText.setText(c+b);
           }
        }; new javax.swing.Timer(400, ac1).start();
    }

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void datapengurus()
    {
        try
        {  
             pst = con.prepareStatement("SELECT COUNT(*) AS data_pengurusCount FROM data_pengurus");
             ResultSet rs = pst.executeQuery();
             while(rs.next())
             {
              int count = rs.getInt("data_pengurusCount");
              //  int count = rs.getInt(1);
 
                
                txtjumlahdatapengurus.setText(String.valueOf(count));
             }
        }
           catch (SQLException ex)
          {
            ex.printStackTrace();
           }
    }
    
    public void dataanggota()
    {
        try
        {  
             pst = con.prepareStatement("SELECT COUNT(*) AS data_anggotaCount FROM data_anggota");
             ResultSet rs = pst.executeQuery();
             while(rs.next())
             {
              int count = rs.getInt("data_anggotaCount");
              //  int count = rs.getInt(1);
 
                
                txtjumlahdataanggota.setText(String.valueOf(count));
             }
        }
           catch (SQLException ex)
          {
            ex.printStackTrace();
           }
    }
    
   public void dataalumni()
    {
        try
        {  
             pst = con.prepareStatement("SELECT COUNT(*) AS data_alumniCount FROM data_alumni");
             ResultSet rs = pst.executeQuery();
             while(rs.next())
             {
              int count = rs.getInt("data_alumniCount");
              //  int count = rs.getInt(1);
 
                
                txtjumlahalumni.setText(String.valueOf(count));
             }
        }
           catch (SQLException ex)
          {
            ex.printStackTrace();
           }
    }
    
             public void connect(){
             
                 try{
                    Class.forName("com.mysql.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/db_ipemarohil_jakarta", "root","");
                    
                 }catch(ClassNotFoundException ex){
                    ex.printStackTrace();
                 }catch(SQLException ex){
                    ex.printStackTrace();
                 }
             }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lb1MovingText = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mainpagebtn = new javax.swing.JPanel();
        mainpage_label = new javax.swing.JLabel();
        data_anggota_btn = new javax.swing.JPanel();
        data_anggota_label = new javax.swing.JLabel();
        data_alumni_btn = new javax.swing.JPanel();
        data_alumni_label = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        logout_label = new javax.swing.JLabel();
        data_pengurus_btn = new javax.swing.JPanel();
        data_pengurus_label = new javax.swing.JLabel();
        data_program_kerja_btn = new javax.swing.JPanel();
        data_program_kerja_label = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtjumlahdatapengurus = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtjumlahdataanggota = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtjumlahalumni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                WindowOpen(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 37, -1, 505));

        lb1MovingText.setBackground(new java.awt.Color(204, 204, 204));
        lb1MovingText.setFont(new java.awt.Font("BIZ UDMincho Medium", 1, 18)); // NOI18N
        lb1MovingText.setForeground(new java.awt.Color(255, 255, 255));
        lb1MovingText.setText("                                                                                                                                                         Selamat Datang Di Sistem Informasi Mahasiswa Ipemarohil Jakarta");
        jPanel1.add(lb1MovingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 5, 1350, 30));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 513));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 365, 125, -1));

        mainpagebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainpagebtnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mainpagebtnMousePressed(evt);
            }
        });
        mainpagebtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainpagebtnKeyPressed(evt);
            }
        });
        mainpagebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpage_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mainpage_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mainpagelogo3.jpg"))); // NOI18N
        mainpage_label.setText("  Beranda");
        mainpagebtn.add(mainpage_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 50));

        jPanel3.add(mainpagebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        data_anggota_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_anggota_btnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                data_anggota_btnMousePressed(evt);
            }
        });

        data_anggota_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        data_anggota_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/data-icon4.png"))); // NOI18N
        data_anggota_label.setText("  Data Anggota");

        javax.swing.GroupLayout data_anggota_btnLayout = new javax.swing.GroupLayout(data_anggota_btn);
        data_anggota_btn.setLayout(data_anggota_btnLayout);
        data_anggota_btnLayout.setHorizontalGroup(
            data_anggota_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_anggota_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(data_anggota_label, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        data_anggota_btnLayout.setVerticalGroup(
            data_anggota_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(data_anggota_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.add(data_anggota_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 230, 50));

        data_alumni_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_alumni_btnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                data_alumni_btnMousePressed(evt);
            }
        });

        data_alumni_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        data_alumni_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/data-icon4.png"))); // NOI18N
        data_alumni_label.setText("  Data Alumni");

        javax.swing.GroupLayout data_alumni_btnLayout = new javax.swing.GroupLayout(data_alumni_btn);
        data_alumni_btn.setLayout(data_alumni_btnLayout);
        data_alumni_btnLayout.setHorizontalGroup(
            data_alumni_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_alumni_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(data_alumni_label, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        data_alumni_btnLayout.setVerticalGroup(
            data_alumni_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(data_alumni_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(data_alumni_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
        });

        logout_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoutlogo.png"))); // NOI18N
        logout_label.setText("  Log Out");

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout_label, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 240, 50));

        data_pengurus_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_pengurus_btnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                data_pengurus_btnMousePressed(evt);
            }
        });

        data_pengurus_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        data_pengurus_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/data-icon4.png"))); // NOI18N
        data_pengurus_label.setText("  Data Pengurus");

        javax.swing.GroupLayout data_pengurus_btnLayout = new javax.swing.GroupLayout(data_pengurus_btn);
        data_pengurus_btn.setLayout(data_pengurus_btnLayout);
        data_pengurus_btnLayout.setHorizontalGroup(
            data_pengurus_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_pengurus_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(data_pengurus_label, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        data_pengurus_btnLayout.setVerticalGroup(
            data_pengurus_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(data_pengurus_label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.add(data_pengurus_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 50));

        data_program_kerja_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_program_kerja_btnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                data_program_kerja_btnMousePressed(evt);
            }
        });

        data_program_kerja_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        data_program_kerja_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/data-icon4.png"))); // NOI18N
        data_program_kerja_label.setText("  Data Program Kerja");

        javax.swing.GroupLayout data_program_kerja_btnLayout = new javax.swing.GroupLayout(data_program_kerja_btn);
        data_program_kerja_btn.setLayout(data_program_kerja_btnLayout);
        data_program_kerja_btnLayout.setHorizontalGroup(
            data_program_kerja_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_program_kerja_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(data_program_kerja_label, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addContainerGap())
        );
        data_program_kerja_btnLayout.setVerticalGroup(
            data_program_kerja_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_program_kerja_btnLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(data_program_kerja_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(data_program_kerja_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 560));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Jumlah Data Pengurus");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 30));

        txtjumlahdatapengurus.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtjumlahdatapengurus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(txtjumlahdatapengurus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 70));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 300, 140));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Jumlah Data Anggota");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 30));

        txtjumlahdataanggota.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtjumlahdataanggota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel14.add(txtjumlahdataanggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 70));

        jPanel6.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 300, 140));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Jumlah Data Alumni");
        jPanel15.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 30));

        txtjumlahalumni.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtjumlahalumni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel15.add(txtjumlahalumni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 70));

        jPanel6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 290, 140));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1080, 310));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Beranda");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 170, 30));

        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 1140, 560));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1370, 600));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("IPEMAROHIL JAKARTA");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 250, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/IPEMAROHIL 5.jpg"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WindowOpen(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WindowOpen
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_WindowOpen

    private void mainpagebtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainpagebtnMousePressed
        // TODO add your handling code here:
         mainpagebtn.setBackground(ClickedColor);
         data_anggota_btn.setBackground(DefaultColor);
         data_alumni_btn.setBackground(DefaultColor);
         data_program_kerja_btn.setBackground(DefaultColor);
         logout.setBackground(DefaultColor);
         data_pengurus_btn.setBackground(DefaultColor);
         mainpage_label.setForeground(Clickedlabelcolor);
         data_anggota_label.setForeground(Defaultlabelcolor);
         data_alumni_label.setForeground(Defaultlabelcolor);
         data_program_kerja_label.setForeground(Defaultlabelcolor);
         
         data_pengurus_label.setForeground(Defaultlabelcolor);
         logout_label.setForeground(Defaultlabelcolor);
    }//GEN-LAST:event_mainpagebtnMousePressed

    private void data_anggota_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_anggota_btnMousePressed
        // TODO add your handling code here:
         mainpagebtn.setBackground(DefaultColor);
         data_anggota_btn.setBackground(ClickedColor);
         data_alumni_btn.setBackground(DefaultColor);
         data_pengurus_btn.setBackground(DefaultColor);
         data_program_kerja_btn.setBackground(DefaultColor);
         logout.setBackground(DefaultColor);
         mainpage_label.setForeground(Defaultlabelcolor);
         data_anggota_label.setForeground(Clickedlabelcolor);
         data_alumni_label.setForeground(Defaultlabelcolor);
         data_program_kerja_label.setForeground(Defaultlabelcolor);
         data_pengurus_label.setForeground(Defaultlabelcolor);
         logout_label.setForeground(Defaultlabelcolor);
    }//GEN-LAST:event_data_anggota_btnMousePressed

    private void data_alumni_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_alumni_btnMousePressed
        // TODO add your handling code here:
         mainpagebtn.setBackground(DefaultColor);
         data_anggota_btn.setBackground(DefaultColor);
         data_alumni_btn.setBackground(ClickedColor);
         data_pengurus_btn.setBackground(DefaultColor);
         data_program_kerja_btn.setBackground(DefaultColor);
         logout.setBackground(DefaultColor);
         mainpage_label.setForeground(Defaultlabelcolor);
         data_anggota_label.setForeground(Defaultlabelcolor);
         data_alumni_label.setForeground(Clickedlabelcolor);
         data_program_kerja_label.setForeground(Defaultlabelcolor);
         data_pengurus_label.setForeground(Defaultlabelcolor);
         logout_label.setForeground(Defaultlabelcolor);
    }//GEN-LAST:event_data_alumni_btnMousePressed

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
         mainpagebtn.setBackground(DefaultColor);
         data_anggota_btn.setBackground(DefaultColor);
         data_alumni_btn.setBackground(DefaultColor);
         data_pengurus_btn.setBackground(DefaultColor);
         data_program_kerja_btn.setBackground(DefaultColor);
         logout.setBackground(ClickedColor);
         mainpage_label.setForeground(Defaultlabelcolor);
         data_anggota_label.setForeground(Defaultlabelcolor);       
         data_alumni_label.setForeground(Defaultlabelcolor);
         data_program_kerja_label.setForeground(Defaultlabelcolor);
         data_pengurus_label.setForeground(Defaultlabelcolor);  
         logout_label.setForeground(Clickedlabelcolor);
    }//GEN-LAST:event_logoutMousePressed

    private void mainpagebtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainpagebtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainpagebtnKeyPressed

    private void mainpagebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainpagebtnMouseClicked
        // TODO add your handling code here:
        Beranda Menu = new Beranda();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(Menu).setVisible(true);
    }//GEN-LAST:event_mainpagebtnMouseClicked

    private void data_anggota_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_anggota_btnMouseClicked
        // TODO add your handling code here:
        DataAnggota Menu = new DataAnggota();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(Menu).setVisible(true);
    }//GEN-LAST:event_data_anggota_btnMouseClicked

    private void data_alumni_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_alumni_btnMouseClicked
        // TODO add your handling code here:
          DataAlumni Menu = new DataAlumni();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(Menu).setVisible(true);
    }//GEN-LAST:event_data_alumni_btnMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginForm(null,true).setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void data_pengurus_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_pengurus_btnMouseClicked
        // TODO add your handling code here:
        DataPengurus Menu = new DataPengurus();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(Menu).setVisible(true);
    }//GEN-LAST:event_data_pengurus_btnMouseClicked

    private void data_pengurus_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_pengurus_btnMousePressed
         mainpagebtn.setBackground(DefaultColor);
         data_anggota_btn.setBackground(DefaultColor);
         data_alumni_btn.setBackground(DefaultColor);
         data_pengurus_btn.setBackground(ClickedColor);
         data_program_kerja_btn.setBackground(DefaultColor);
         logout.setBackground(DefaultColor);
         mainpage_label.setForeground(Defaultlabelcolor);
         data_anggota_label.setForeground(Defaultlabelcolor);       
         data_alumni_label.setForeground(Defaultlabelcolor);
         data_program_kerja_label.setForeground(Defaultlabelcolor);
         data_pengurus_label.setForeground(Clickedlabelcolor);  
         logout_label.setForeground(Defaultlabelcolor);
    }//GEN-LAST:event_data_pengurus_btnMousePressed

    private void data_program_kerja_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_program_kerja_btnMouseClicked
         DataProgramKerja Menu = new DataProgramKerja();
         jDesktopPane1.removeAll();
         jDesktopPane1.add(Menu).setVisible(true);
    }//GEN-LAST:event_data_program_kerja_btnMouseClicked

    private void data_program_kerja_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_program_kerja_btnMousePressed
        // TODO add your handling code here:
         mainpagebtn.setBackground(DefaultColor);
         data_anggota_btn.setBackground(DefaultColor);
         data_alumni_btn.setBackground(DefaultColor);
         data_pengurus_btn.setBackground(DefaultColor);
         data_program_kerja_btn.setBackground(ClickedColor);
         logout.setBackground(DefaultColor);
         mainpage_label.setForeground(Defaultlabelcolor);
         data_anggota_label.setForeground(Defaultlabelcolor);       
         data_alumni_label.setForeground(Defaultlabelcolor);
         data_program_kerja_label.setForeground(Clickedlabelcolor);
         data_pengurus_label.setForeground(Defaultlabelcolor);  
         logout_label.setForeground(Defaultlabelcolor);
    }//GEN-LAST:event_data_program_kerja_btnMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel data_alumni_btn;
    private javax.swing.JLabel data_alumni_label;
    private javax.swing.JPanel data_anggota_btn;
    private javax.swing.JLabel data_anggota_label;
    private javax.swing.JPanel data_pengurus_btn;
    private javax.swing.JLabel data_pengurus_label;
    private javax.swing.JPanel data_program_kerja_btn;
    private javax.swing.JLabel data_program_kerja_label;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lb1MovingText;
    private javax.swing.JPanel logout;
    private javax.swing.JLabel logout_label;
    private javax.swing.JLabel mainpage_label;
    private javax.swing.JPanel mainpagebtn;
    private javax.swing.JLabel txtjumlahalumni;
    private javax.swing.JLabel txtjumlahdataanggota;
    private javax.swing.JLabel txtjumlahdatapengurus;
    // End of variables declaration//GEN-END:variables
}
